services:
    security:
        class: AT\votacionBundle\Services\SecurityService
        arguments: ["@service_container"]
    validate:
        class: AT\votacionBundle\Services\ValidateService
    mail:
        class: AT\votacionBundle\Services\MailService
        arguments: ["@mailer", "@templating"]
