parameters:
#    votacion.example.class: AT\votacionBundle\Example

services:
    security:
        class: AT\votacionBundle\Services\SecurityService
        arguments: ["@doctrine", "@session"]
    validate:
        class: AT\votacionBundle\Services\ValidateService
